name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.4

      - name: Print env
        run: |
          env
          echo -------
          echo ${{ github.ref }}
          echo -------
          echo ${{ github.ref_name }}

      - name: Build Binary
        run: make build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # settings/Actions/General (Read and write permissions)
          files: |
            dist/webdav-darwin-amd64.tar.gz
            dist/webdav-darwin-arm64.tar.gz
            dist/webdav-linux-amd64.tar.gz
            dist/webdav-windows-amd64.zip

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker
        run: |
          rm -rf dist
          docker build --no-cache --rm --tag tmaize/webdav:${{ github.ref_name }} .
          docker push tmaize/webdav:${{ github.ref_name }}
